### PR TITLE
add lb as tooling wants it

### PR DESCRIPTION
**Pull request by carlosdem**

### CODE REVIEW

**Comment by jriddell** [comment]
what is this building?

**Comment by carlosdem** [comment]
it is for the mobile/pine images - https://build.neon.kde.org/view/img/  
I am trying to get my head around all the mobile(y) stuff with a view at reviving it a bit

**Comment by jriddell** [comment]
well good luck but it's all since bitrotted lots.  for devices like these there usually needs to be a custom made linux build and other stuff like drivers that needs special-cased included and of course you need the device in question to test on.

**Comment by carlosdem** [comment]
not necessarily for those specific devices but at least get my head around the tech involved and see what is down the track

**Pull request merged**
